name: app_manajemen_umkm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar:
  lottie:
  flutter_animate:
  bounce_tapper:
  animated_splash_screen:
  path_provider:
  image_picker:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lotties/

